package br.com.bhsoftworks.webcolaboradores.model;
// Generated 17/09/2017 19:41:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Colaborador generated by hbm2java
 */
@Entity
@Table(name="Colaborador"
    ,catalog="bd_colaborador"
)
@XmlRootElement
public class Colaborador  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String login;
     private int perfil;
     private String senha;

    public Colaborador() {
    }

    public Colaborador(String nome, String login, int perfil, String senha) {
       this.nome = nome;
       this.login = login;
       this.perfil = perfil;
       this.senha = senha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nome", nullable=false, length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="login", nullable=false, length=60)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="perfil", nullable=false)
    public int getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(int perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="senha", nullable=false, length=60)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


